### ISSUE TITLE
Tracker for (pending) Distro additions to Quickemu

### ISSUE THREAD

**Issue by daPhipz** [quickemu-project/quickemu-icons#12]
This issue tracks the [PRs](https://github.com/wimpysworld/quickemu/pulls) that add a distro to `quickget`, so that we can provide the icon when the PRs land.

#### To Do:
- [ ] **GhostBSD:**
- [ ] **Haiku:**
  - [x] https://github.com/quickemu-project/quickemu/pull/289
- [ ] **KolibriOS:**
  - [x] https://github.com/quickemu-project/quickemu/pull/286
- [ ] **LMDE:**
  - [x] https://github.com/quickemu-project/quickemu/pull/484
- [ ] **LudOS:** https://github.com/kivutar/ludo-assets/blob/e72d3737fb5d35128de1eb72498a8b8acaab52bb/icon.svg
  - [ ] https://github.com/quickemu-project/quickemu/pull/407
- [ ] **netboot.xyz:** 
- [ ] **NetBSD:**
  - [x] https://github.com/quickemu-project/quickemu/commit/bd87f98224b0569e4252e7a97e94648cd2de4355
- [ ] **Oracle Linux:**
  - [x] https://github.com/wimpysworld/quickemu/pull/235
- [ ] **ReactOS:**
  - [x] https://github.com/quickemu-project/quickemu/pull/423
- [ ] **Slackware:**
  - [x] https://github.com/quickemu-project/quickemu/pull/369
- [ ] **Tails:**
  - [x] https://github.com/quickemu-project/quickemu/pull/308

#### Done:
<details>
<summary>Click to expand</summary>

- [x] **Alma Linux:**
  - [x] https://github.com/quickemu-project/quickemu/pull/259
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/42
- [x] **Alpine Linux:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/45
  - [x] https://github.com/quickemu-project/quickemu/pull/298
- [x] **Android x86:**
  - [x] https://github.com/wimpysworld/quickemu/pull/174
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/44
- [x] **Arch Linux:**
  - [x] #3 
  - [x] https://github.com/wimpysworld/quickemu/pull/146
- [x] **Archcraft:**
  - [x] https://github.com/quickemu-project/quickemu/pull/565
- [x] **Arco Linux:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/46
  - [x] https://github.com/quickemu-project/quickemu/pull/284
- [x] **Batocera.linux:** https://batocera.org/
  - [x] https://github.com/quickemu-project/quickemu/pull/403
- [x] **CachyOS:**
  - [x] #41
  - [x] https://github.com/quickemu-project/quickemu/pull/245
- [x] **CentOS Stream:**
  - [x] https://github.com/quickemu-project/quickemu/pull/464
- [x] **Debian:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/40
  - [x] https://github.com/quickemu-project/quickemu/pull/243
- [x] **Deepin:**
  - [x] https://github.com/quickemu-project/quickemu/pull/475
- [x] **Devuan:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/52
  - [x] https://github.com/quickemu-project/quickemu/pull/345
  - [x] https://github.com/quickemu-project/quickemu/commit/af7ed8c2d6aec460e40b03af429de5e23b1e762c
- [x] **DragonFlyBSD:**
  - [x] https://github.com/quickemu-project/quickemu/pull/378
- [x] **EndeavourOS:**
  - [x] https://github.com/quickemu-project/quickemu/pull/449
- [x] **FreeBSD:**
  - [x] https://github.com/wimpysworld/quickemu/pull/62
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/43
- [x] **FreeDOS:**
  - [x] https://github.com/quickemu-project/quickemu/pull/374
- [x] **Garuda Linux:**
  - [x] https://github.com/Lukewh/quickemu-icons/pull/17
  - [x] https://github.com/wimpysworld/quickemu/pull/197
- [x] **Gentoo:**
  - [x] https://github.com/quickemu-project/quickemu/pull/255
- [x] **Kali Linux:**
  - [x] #3 
  - [x] https://github.com/wimpysworld/quickemu/pull/148
- [x] **KDE Neon:**
  - [x] https://github.com/Lukewh/quickemu-icons/pull/22
  - [x] https://github.com/wimpysworld/quickemu/pull/207
- [x] **Manjaro:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/47
  - [x] https://github.com/quickemu-project/quickemu/pull/296
- [x] **MX Linux:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/48
  - [x] https://github.com/quickemu-project/quickemu/pull/322
  - [x] https://github.com/quickemu-project/quickemu/pull/292
- [x] **OpenBSD:**
  - [x] #3 
  - [x] https://github.com/wimpysworld/quickemu/pull/129
- [x] **Regolith Linux:**
  - [x] https://github.com/Lukewh/quickemu-icons/pull/16
  - [x] https://github.com/wimpysworld/quickemu/pull/190
- [x] **Rocky Linux:**
  - [x] https://github.com/Lukewh/quickemu-icons/pull/21
  - [x] https://github.com/wimpysworld/quickemu/pull/184
- [x] **Solus:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/34
  - [x] https://github.com/wimpysworld/quickemu/pull/208
- [x] **Void Linux:**
  - [x] https://github.com/quickemu-project/quickemu-icons/pull/51
  - [x] https://github.com/quickemu-project/quickemu/pull/322
  - [x] https://github.com/quickemu-project/quickemu/pull/321
- [x] **Zorin OS:**
  - [x] https://github.com/Lukewh/quickemu-icons/pull/23
  - [x] https://github.com/wimpysworld/quickemu/pull/185
</details>

**Comment by daPhipz** [comment]
@Lukewh are you able to tick/untick boxes here, even if I created the issue?

**Comment by Lukewh** [comment]
Looks like it :+1:

**Comment by philclifford** [comment]
Looks like we'll need to [get permission](https://www.haiku-inc.org/trademarks/allowed_usage/) to use/combine the Haiku artwork.

**Comment by daPhipz** [comment]
> As part of a notice that your product incorporates [...] Haiku

Isn't this the case with us here? 🤔

**Comment by philclifford** [comment]
Re [BlendOS](https://github.com/quickemu-project/quickemu/pull/639) - you could check with Rudra, but I think the logo is here: https://github.com/blend-os/filesystem-blend/blob/main/blendos-logo.svg alongside some text logos...

**Comment by philclifford** [comment]
OpenIndiana PR is close-to-ready: https://github.com/quickemu-project/quickemu/pull/697

**Comment by flexiondotorg** [comment]
Closing this as it is no longer current.
